import { blast } from '@/config/tokens/blast';
import { formatTokenKey, formatToken } from '../helpers';

const contracts: { [key: number]: any } = {
  81457: {
    PositionManager: '0x434575EaEa081b735C985FA9bf63CD7b87e227F9',
    Factory: '0x71b08f13B3c3aF35aAdEb3949AFEb1ded1016127',
  },
};

const tokens: { [key: number]: any } = {
  81457: [
    blast['eth'],
    blast['weth'],
    blast['usdb'],
    blast['yes'],
    blast['usde'],
    blast['ezeth'],
    blast['pac'],
    blast['weeth'],
    blast['usd+'],
    blast['wrseth'],
    blast['rbx'],
    blast['andy'],
    blast['bpepe'],
    blast['ole'],
    blast['sUSDe'],
    blast['kap'],
    blast['juice'],
    blast['bwool'],
    blast['sss'],
    blast['yield'],
    blast['deth'],
    blast['wbtc'],
    blast['mwstETH-WPUNKS:20'],
    blast['axlusdc'],
    blast['mwstETH-WPUNKS:40'],
    blast['mia'],
    blast['sfrxETH'],
    blast['bus'],
    blast['pxeth'],
    blast['tes'],
    blast['early'],
    blast['baja'],
    blast['core'],
    blast['ese'],
    blast['dusd'],
    blast['ankrETH'],
    blast['sfrax'],
    blast['bag'],
    blast['dola'],
    blast['glory'],
    blast['inETH'],
    blast['mWETH-PPG:5'],
    blast['orbit'],
    blast['mblastopians'],
    blast['ohno'],
    blast['bepe'],
    blast['bns'],
    blast['pump'],
    blast['pstake'],
    blast['zai'],
    blast['bnd'],
    blast['ethx'],
    blast['ghost'],
    blast['big'],
    blast['aura'],
    blast['upt'],
    blast['$wai'],
    blast['wels'],
    blast['usb'],
    blast['pacm'],
    blast['usdc+'],
    blast['alien'],
    blast['swim'],
    blast['vroom'],
    blast['peace'],
    blast['ankr'],
    blast['mWETH-PPG:10'],
    blast['nptx'],
    blast['ai'],
    blast['usdbx'],
    blast['fxs'],
  ]
    .map((token) => formatToken(token))
    .reduce((acc, curr) => ({ ...acc, [formatTokenKey(curr)]: curr }), {}),
};

export default {
  contracts,
  fees: [500, 3000, 10000],
  defaultFee: 500,
  tokens,
};
