export const ODYSSEY_GAME_DAPPS = [
  {
    key: 1,
    sort: 1,
    name: 'Pancake Swap',
    icon: '/images/odyssey/v2-1/dapps/pancake-swap.svg',
    card: '/images/odyssey/v2-1/dapps/pancake-swap.png',
    link: '',
  },
  {
    key: 2,
    sort: 2,
    name: 'Xfai',
    icon: '/images/odyssey/v2-1/dapps/xfai.svg',
    card: '/images/odyssey/v2-1/dapps/xfai.png',
    link: '',
  },
  {
    key: 3,
    sort: 3,
    name: 'HorizonDex',
    icon: '/images/odyssey/v2-1/dapps/horizon-dex.svg',
    card: '/images/odyssey/v2-1/dapps/horizon-dex.png',
    link: '',
  },
  {
    key: 4,
    sort: 4,
    name: 'iZiSwap',
    icon: '/images/odyssey/v2-1/dapps/izi-swap.svg',
    card: '/images/odyssey/v2-1/dapps/izi-swap.png',
    link: '',
  },
  {
    key: 5,
    sort: 5,
    name: 'SyncSwap',
    icon: '/images/odyssey/v2-1/dapps/sync-swap.svg',
    card: '/images/odyssey/v2-1/dapps/sync-swap.png',
    link: '',
  },
  {
    key: 6,
    sort: 6,
    name: 'Velocore V2',
    icon: '/images/odyssey/v2-1/dapps/velocore-v2.svg',
    card: '/images/odyssey/v2-1/dapps/velocore-v2.png',
    link: '',
  },
  {
    key: 7,
    sort: 7,
    name: 'Lynex',
    icon: '/images/odyssey/v2-1/dapps/lynex.svg',
    card: '/images/odyssey/v2-1/dapps/lynex.png',
    link: '',
  },
  {
    key: 8,
    sort: 8,
    name: 'LayerBank',
    icon: '/images/odyssey/v2-1/dapps/layer-bank.svg',
    card: '/images/odyssey/v2-1/dapps/layer-bank.png',
    link: '',
  },
  {
    key: 9,
    sort: 9,
    name: 'Mendi Finance',
    icon: '/images/odyssey/v2-1/dapps/mendi-finance.svg',
    card: '/images/odyssey/v2-1/dapps/mendi-finance.png',
    link: '',
  },
  {
    key: 10,
    sort: 10,
    name: 'ZeroLend',
    icon: '/images/odyssey/v2-1/dapps/zero-lend.svg',
    card: '/images/odyssey/v2-1/dapps/zero-lend.png',
    link: '',
  },
  {
    key: 11,
    sort: 11,
    name: 'Stargate',
    icon: '/images/odyssey/v2-1/dapps/stargate.svg',
    card: '/images/odyssey/v2-1/dapps/stargate.png',
    link: '',
  },
  {
    key: 12,
    sort: 12,
    name: 'Rubic Bridge',
    icon: '/images/odyssey/v2-1/dapps/rubic-bridge.svg',
    card: '/images/odyssey/v2-1/dapps/rubic-bridge.png',
    link: '',
  },
  {
    key: 13,
    sort: 13,
    name: 'LiFi',
    icon: '/images/odyssey/v2-1/dapps/lifi.svg',
    card: '/images/odyssey/v2-1/dapps/lifi.png',
    link: '',
  },
  {
    key: 14,
    sort: 14,
    name: 'Swing Aggregator',
    icon: '/images/odyssey/v2-1/dapps/swing-aggregator.svg',
    card: '/images/odyssey/v2-1/dapps/swing-aggregator.png',
    link: '',
  },
  {
    key: 15,
    sort: 15,
    name: 'Orbiter Bridge',
    icon: '/images/odyssey/v2-1/dapps/orbiter-bridge.svg',
    card: '/images/odyssey/v2-1/dapps/orbiter-bridge.png',
    link: '',
  },
  {
    key: 16,
    sort: 16,
    name: 'XY Finance',
    icon: '/images/odyssey/v2-1/dapps/xy-finance.svg',
    card: '/images/odyssey/v2-1/dapps/xy-finance.png',
    link: '',
  },
  {
    key: 17,
    sort: 17,
    name: 'Metavault',
    icon: '/images/odyssey/v2-1/dapps/metavault.svg',
    card: '/images/odyssey/v2-1/dapps/metavault.png',
    link: '',
  },
  {
    key: 18,
    sort: 18,
    name: 'Sushi Swap',
    icon: '/images/odyssey/v2-1/dapps/sushi-swap.svg',
    card: '/images/odyssey/v2-1/dapps/sushi-swap.png',
    link: '',
  },
  {
    key: 19,
    sort: 19,
    name: 'Granary Finance',
    icon: '/images/odyssey/v2-1/dapps/granary-finance.svg',
    card: '/images/odyssey/v2-1/dapps/granary-finance.png',
    link: '',
  },
  {
    key: 20,
    sort: 20,
    name: 'Gravita Protocol',
    icon: '/images/odyssey/v2-1/dapps/gravita-protocol.svg',
    card: '/images/odyssey/v2-1/dapps/gravita-protocol.png',
    link: '',
  },
  {
    key: 21,
    sort: 21,
    name: 'Celer',
    icon: '/images/odyssey/v2-1/dapps/celer.svg',
    card: '/images/odyssey/v2-1/dapps/celer.png',
    link: '',
  },
  {
    key: 22,
    sort: 22,
    name: 'Connext Bridge',
    icon: '/images/odyssey/v2-1/dapps/connext-bridge.svg',
    card: '/images/odyssey/v2-1/dapps/connext-bridge.png',
    link: '',
  },
  {
    key: 23,
    sort: 23,
    name: 'Deri Protocol',
    icon: '/images/odyssey/v2-1/dapps/deri-protocol.svg',
    card: '/images/odyssey/v2-1/dapps/deri-protocol.png',
    link: '',
  },
  {
    key: 24,
    sort: 24,
    name: 'Ledgity Yield',
    icon: '/images/odyssey/v2-1/dapps/ledgity-yield.svg',
    card: '/images/odyssey/v2-1/dapps/ledgity-yield.png',
    link: '',
  },
  {
    key: 25,
    sort: 25,
    name: 'LyveFinance',
    icon: '/images/odyssey/v2-1/dapps/lyve-finance.svg',
    card: '/images/odyssey/v2-1/dapps/lyve-finance.png',
    link: '',
  },
  {
    key: 26,
    sort: 26,
    name: 'Nile',
    icon: '/images/odyssey/v2-1/dapps/nile.svg',
    card: '/images/odyssey/v2-1/dapps/nile.png',
    link: '',
  },
  {
    key: 27,
    sort: 27,
    name: 'Satori',
    icon: '/images/odyssey/v2-1/dapps/satori.svg',
    card: '/images/odyssey/v2-1/dapps/satori.png',
    link: '',
  },
  {
    key: 28,
    sort: 28,
    name: 'Secta Finance',
    icon: '/images/odyssey/v2-1/dapps/secta-finance.svg',
    card: '/images/odyssey/v2-1/dapps/secta-finance.png',
    link: '',
  },
  {
    key: 29,
    sort: 29,
    name: 'zkDX',
    icon: '/images/odyssey/v2-1/dapps/zkdx.svg',
    card: '/images/odyssey/v2-1/dapps/zkdx.png',
    link: '',
  },
  {
    key: 30,
    sort: 30,
    name: 'StakeStone',
    icon: '/images/odyssey/v2-1/dapps/stake-stone.svg',
    card: '/images/odyssey/v2-1/dapps/stake-stone.png',
    link: '',
  },
  {
    key: 31,
    sort: 31,
    name: 'Across Protocol',
    icon: '/images/odyssey/v2-1/dapps/across-protocol.svg',
    card: '/images/odyssey/v2-1/dapps/across-protocol.png',
    link: '',
  },
  {
    key: 32,
    sort: 32,
    name: 'Interport',
    icon: '/images/odyssey/v2-1/dapps/interport.svg',
    card: '/images/odyssey/v2-1/dapps/interport.png',
    link: '',
  },
  {
    key: 33,
    sort: 33,
    name: 'Teahouse',
    icon: '/images/odyssey/v2-1/dapps/teahouse.svg',
    card: '/images/odyssey/v2-1/dapps/teahouse.png',
    link: '',
  },
  {
    key: 34,
    sort: 34,
    name: 'Beefy',
    icon: '/images/odyssey/v2-1/dapps/beefy.svg',
    card: '/images/odyssey/v2-1/dapps/beefy.png',
    link: '',
  },
  {
    key: 35,
    sort: 35,
    name: 'Kelp',
    icon: '/images/odyssey/v2-1/dapps/kelp.svg',
    card: '/images/odyssey/v2-1/dapps/kelp.png',
    link: '',
  },
  {
    key: 36,
    sort: 36,
    name: 'Davos',
    icon: '',
    card: '/images/odyssey/v2-1/dapps/davos.png',
    link: '',
  },
];

export enum DAPP_STATUS {
  UNFINISHED,
  FINISHED,
  PENDING,
}

export const DAPP_SPLIT = 6;
