export const ODYSSEY_GAME_DAPPS = [
  {
    id: 110,
    name: 'Pancake Swap',
    icon: '/images/odyssey/v2-1/dapps/pancake-swap.svg',
    card: '/images/odyssey/v2-1/dapps/pancake-swap.png',
    link: '',
  },
  {
    id: 111,
    name: 'Xfai',
    icon: '/images/odyssey/v2-1/dapps/xfai.svg',
    card: '/images/odyssey/v2-1/dapps/xfai.png',
    link: '',
  },
  {
    id: 112,
    name: 'HorizonDex',
    icon: '/images/odyssey/v2-1/dapps/horizon-dex.svg',
    card: '/images/odyssey/v2-1/dapps/horizon-dex.png',
    link: '',
  },
  {
    id: 113,
    name: 'iZiSwap',
    icon: '/images/odyssey/v2-1/dapps/izi-swap.svg',
    card: '/images/odyssey/v2-1/dapps/izi-swap.png',
    link: '',
  },
  {
    id: 114,
    name: 'SyncSwap',
    icon: '/images/odyssey/v2-1/dapps/sync-swap.svg',
    card: '/images/odyssey/v2-1/dapps/sync-swap.png',
    link: '',
  },
  {
    id: 115,
    name: 'Velocore V2',
    icon: '/images/odyssey/v2-1/dapps/velocore-v2.svg',
    card: '/images/odyssey/v2-1/dapps/velocore-v2.png',
    link: '',
  },
  {
    id: 116,
    name: 'Lynex',
    icon: '/images/odyssey/v2-1/dapps/lynex.svg',
    card: '/images/odyssey/v2-1/dapps/lynex.png',
    link: '',
  },
  {
    id: 125,
    name: 'LayerBank',
    icon: '/images/odyssey/v2-1/dapps/layer-bank.svg',
    card: '/images/odyssey/v2-1/dapps/layer-bank.png',
    link: '',
  },
  {
    id: 126,
    name: 'Mendi Finance',
    icon: '/images/odyssey/v2-1/dapps/mendi-finance.svg',
    card: '/images/odyssey/v2-1/dapps/mendi-finance.png',
    link: '',
  },
  {
    id: 127,
    name: 'ZeroLend',
    icon: '/images/odyssey/v2-1/dapps/zero-lend.svg',
    card: '/images/odyssey/v2-1/dapps/zero-lend.png',
    link: '',
  },
  {
    id: 124,
    name: 'Stargate',
    icon: '/images/odyssey/v2-1/dapps/stargate.svg',
    card: '/images/odyssey/v2-1/dapps/stargate.png',
    link: '',
  },
  {
    id: 120,
    name: 'Rubic Bridge',
    icon: '/images/odyssey/v2-1/dapps/rubic-bridge.svg',
    card: '/images/odyssey/v2-1/dapps/rubic-bridge.png',
    link: '',
  },
  {
    id: 121,
    name: 'LiFi',
    icon: '/images/odyssey/v2-1/dapps/lifi.svg',
    card: '/images/odyssey/v2-1/dapps/lifi.png',
    link: '',
  },
  {
    id: 122,
    name: 'Swing Aggregator',
    icon: '/images/odyssey/v2-1/dapps/swing-aggregator.svg',
    card: '/images/odyssey/v2-1/dapps/swing-aggregator.png',
    link: '',
  },
  {
    id: 123,
    name: 'Orbiter Bridge',
    icon: '/images/odyssey/v2-1/dapps/orbiter-bridge.svg',
    card: '/images/odyssey/v2-1/dapps/orbiter-bridge.png',
    link: '',
  },
  {
    id: 117,
    name: 'XY Finance',
    icon: '/images/odyssey/v2-1/dapps/xy-finance.svg',
    card: '/images/odyssey/v2-1/dapps/xy-finance.png',
    link: '',
  },
  {
    id: 118,
    name: 'Metavault',
    icon: '/images/odyssey/v2-1/dapps/metavault.svg',
    card: '/images/odyssey/v2-1/dapps/metavault.png',
    link: '',
  },
  {
    id: 119,
    name: 'Sushi Swap',
    icon: '/images/odyssey/v2-1/dapps/sushi-swap.svg',
    card: '/images/odyssey/v2-1/dapps/sushi-swap.png',
    link: '',
  },
  {
    id: 128,
    name: 'Granary Finance',
    icon: '/images/odyssey/v2-1/dapps/granary-finance.svg',
    card: '/images/odyssey/v2-1/dapps/granary-finance.png',
    link: '',
  },
  {
    id: 129,
    name: 'Gravita Protocol',
    icon: '/images/odyssey/v2-1/dapps/gravita-protocol.svg',
    card: '/images/odyssey/v2-1/dapps/gravita-protocol.png',
    link: '',
  },
  {
    id: 21,
    name: 'Celer',
    icon: '/images/odyssey/v2-1/dapps/celer.svg',
    card: '/images/odyssey/v2-1/dapps/celer.png',
    link: '',
  },
  {
    id: 22,
    name: 'Connext Bridge',
    icon: '/images/odyssey/v2-1/dapps/connext-bridge.svg',
    card: '/images/odyssey/v2-1/dapps/connext-bridge.png',
    link: '',
  },
  {
    id: 23,
    name: 'Deri Protocol',
    icon: '/images/odyssey/v2-1/dapps/deri-protocol.svg',
    card: '/images/odyssey/v2-1/dapps/deri-protocol.png',
    link: '',
  },
  {
    id: 132,
    name: 'Ledgity Yield',
    icon: '/images/odyssey/v2-1/dapps/ledgity-yield.svg',
    card: '/images/odyssey/v2-1/dapps/ledgity-yield.png',
    link: '',
  },
  {
    id: 25,
    name: 'LyveFinance',
    icon: '/images/odyssey/v2-1/dapps/lyve-finance.svg',
    card: '/images/odyssey/v2-1/dapps/lyve-finance.png',
    link: '',
  },
  {
    id: 26,
    name: 'Nile',
    icon: '/images/odyssey/v2-1/dapps/nile.svg',
    card: '/images/odyssey/v2-1/dapps/nile.png',
    link: '',
  },
  {
    id: 27,
    name: 'Satori',
    icon: '/images/odyssey/v2-1/dapps/satori.svg',
    card: '/images/odyssey/v2-1/dapps/satori.png',
    link: '',
  },
  {
    id: 28,
    name: 'Secta Finance',
    icon: '/images/odyssey/v2-1/dapps/secta-finance.svg',
    card: '/images/odyssey/v2-1/dapps/secta-finance.png',
    link: '',
  },
  {
    id: 29,
    name: 'zkDX',
    icon: '/images/odyssey/v2-1/dapps/zkdx.svg',
    card: '/images/odyssey/v2-1/dapps/zkdx.png',
    link: '',
  },
  {
    id: 30,
    name: 'StakeStone',
    icon: '/images/odyssey/v2-1/dapps/stake-stone.svg',
    card: '/images/odyssey/v2-1/dapps/stake-stone.png',
    link: '',
  },
  {
    id: 31,
    name: 'Across Protocol',
    icon: '/images/odyssey/v2-1/dapps/across-protocol.svg',
    card: '/images/odyssey/v2-1/dapps/across-protocol.png',
    link: '',
  },
  {
    id: 32,
    name: 'Interport',
    icon: '/images/odyssey/v2-1/dapps/interport.svg',
    card: '/images/odyssey/v2-1/dapps/interport.png',
    link: '',
  },
  {
    id: 131,
    name: 'Teahouse',
    icon: '/images/odyssey/v2-1/dapps/teahouse.svg',
    card: '/images/odyssey/v2-1/dapps/teahouse.png',
    link: '',
  },
  {
    id: 130,
    name: 'Beefy',
    icon: '/images/odyssey/v2-1/dapps/beefy.svg',
    card: '/images/odyssey/v2-1/dapps/beefy.png',
    link: '',
  },
  {
    id: 133,
    name: 'Kelp',
    icon: '/images/odyssey/v2-1/dapps/kelp.svg',
    card: '/images/odyssey/v2-1/dapps/kelp.png',
    link: '',
  },
  {
    id: 36,
    name: 'BLADE',
    icon: '/images/odyssey/v2-1/dapps/blade.svg',
    card: '/images/odyssey/v2-1/dapps/blade.png',
    link: '',
  },
];

export enum DAPP_STATUS {
  UNFINISHED,
  FINISHED,
  PENDING,
}
