import { arbitrum } from '@/config/tokens/arbitrum';
import { avalanche } from '@/config/tokens/avalanche';
import { base } from '@/config/tokens/base';
import { gnosis } from '@/config/tokens/gnosis';
import { metis } from '@/config/tokens/metis';
import { optimism } from '@/config/tokens/optimism';
import { polygon } from '@/config/tokens/polygon';
import { scroll } from '@/config/tokens/scroll';
import { zkSync } from '@/config/tokens/zkSync';

const WETH_TOKEN = { name: 'Wrapped Ether', symbol: 'WETH', decimals: 18 };
const MATIC_TOKEN = { name: 'Matic', symbol: 'MATIC', decimals: 18 };
const WMATIC_TOKEN = { name: 'Wrapped Matic', symbol: 'WMATIC', decimals: 18 };
const ownerId = 'bluebiu.near';
const nodeUrl = 'https://rpc.mainnet.near.org';
const CONTRACT_ABI = {
  wrappedTokenGatewayV3ABI:
    'https://raw.githubusercontent.com/corndao/aave-v3-bos-app/main/abi/WrappedTokenGatewayV3ABI.json',
  erc20Abi: 'https://raw.githubusercontent.com/corndao/aave-v3-bos-app/main/abi/ERC20Permit.json',
  aavePoolV3ABI: 'https://raw.githubusercontent.com/corndao/aave-v3-bos-app/main/abi/AAVEPoolV3.json',
  variableDebtTokenABI: 'https://raw.githubusercontent.com/corndao/aave-v3-bos-app/main/abi/VariableDebtToken.json',
  walletBalanceProviderABI:
    'https://raw.githubusercontent.com/corndao/aave-v3-bos-app/main/abi/WalletBalanceProvider.json'
};
const heroData = ['Net Worth', 'Net APY', 'Health Factor'];
const baseConfig = { ownerId, nodeUrl, heroData };
const basic = {
  name: 'AAVE V3',
  icon: '/assets/images/061_094-aave1.png',
  // data: 'bluebiu.near/widget/Lending.Data.Liquity',
  // handler: 'bluebiu.near/widget/Lending.Handler.Liquity',
  type: 'aave-v3',
  loaderName: 'AaveV3'
};

const rewardToken = [
  {
    address: '',
    // decimals: 18,
    symbol: 'METIS',
    name: 'METIS',
    icon: '',
    unclaimed: ''
  }
];

const networks = {
  // scroll
  534352: {
    config: {
      ...baseConfig,
      chainName: 'Scroll',
      nativeCurrency: scroll['eth'],
      nativeWrapCurrency: scroll['weth'],
      rpcUrl: 'https://1rpc.io/scroll',
      aavePoolV3Address: '0x11fCfe756c05AD438e312a7fd934381537D3cFfe',
      PoolDataProvider: '0xa99F4E69acF23C6838DE90dD1B5c02EA928A53ee',
      wrappedTokenGatewayV3Address: '0xd91d1331db4F436DaF47Ec9Dd86deCb8EEF946B4',
      balanceProviderAddress: '0xE51642875Af07Fea1B03d821E41a9DB24bC4447E',
      incentivesProxy: '0xa3f3100C4f1D0624DB9DB97b40C13885Ce297799' //CLAIM
    },
    rawMarkets: [
      // {
      //   id: '1',
      //   underlyingAsset: scroll['weth'].address,
      //   icon: scroll['eth'].icon,
      //   decimals: 18,
      //   name: 'Ethereum',
      //   symbol: 'ETH',
      //   supplyAPY: '',
      //   usageAsCollateralEnabled: true,
      //   borrowingEnabled: true,
      //   aTokenAddress: '0xf301805be1df81102c957f6d4ce29d2b8c056b2a',
      //   variableDebtTokenAddress: '0xfD7344CeB1Df9Cf238EcD667f4A6F99c6Ef44a56',
      //   isIsolated: false,
      //   availableLiquidity: 0,
      //   availableLiquidityUSD: '',
      //   variableBorrowAPY: '',
      //   supportPermit: false,
      //   LTV: 0,
      //   supportBorrow: true
      // },
      {
        id: '2',
        underlyingAsset: scroll['weth'].address,
        icon: scroll['weth'].icon,
        decimals: scroll['weth'].decimals,
        symbol: scroll['weth'].symbol,
        name: scroll['weth'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: false,
        aTokenAddress: '0xf301805be1df81102c957f6d4ce29d2b8c056b2a',
        variableDebtTokenAddress: '0xfD7344CeB1Df9Cf238EcD667f4A6F99c6Ef44a56',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: false
      },
      {
        id: '3',
        underlyingAsset: scroll['wsteth'].address,
        icon: scroll['wsteth'].icon,
        decimals: scroll['wsteth'].decimals,
        symbol: scroll['wsteth'].symbol,
        name: scroll['wsteth'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x5B1322eeb46240b02e20062b8F0F9908d525B09c',
        variableDebtTokenAddress: '0x8a035644322129800C3f747f54Db0F4d3c0A2877',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '4',
        underlyingAsset: scroll['usdc'].address,
        icon: scroll['usdc'].icon,
        decimals: scroll['usdc'].decimals,
        symbol: scroll['usdc'].symbol,
        name: scroll['usdc'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x1D738a3436A8C49CefFbaB7fbF04B660fb528CbD',
        variableDebtTokenAddress: '0x3d2E209af5BFa79297C88D6b57F89d792F6E28EE',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '5',
        underlyingAsset: scroll['we-eth'].address,
        icon: scroll['we-eth'].icon,
        decimals: scroll['we-eth'].decimals,
        symbol: scroll['we-eth'].symbol,
        name: scroll['we-eth'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0xd80A5e16DBDC52Bd1C947CEDfA22c562Be9129C8',
        variableDebtTokenAddress: '0x009D88C6a6B4CaA240b71C98BA93732e26F2A55A',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      }
    ],
    CONTRACT_ABI
  },
  // metis
  1088: {
    config: {
      ...baseConfig,
      chainName: 'Metis',
      nativeCurrency: metis['eth'],
      nativeWrapCurrency: metis['weth'],
      rpcUrl: 'https://metis-pokt.nodies.app',
      aavePoolV3Address: '0x90df02551bB792286e8D4f13E0e357b4Bf1D6a57',
      PoolDataProvider: '0x99411FC17Ad1B56f49719E3850B2CDcc0f9bBFd8',
      wrappedTokenGatewayV3Address: '0xFF75A4B698E3Ec95E608ac0f22A03B8368E05F5D',
      balanceProviderAddress: '0x1df710eb1E2FD9C21494aF2BFb1F210a4185885b',
      incentivesProxy: '0x30C1b8F0490fa0908863d6Cbd2E36400b4310A6B', //CLAIM
      rewardAddress: '0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000'
    },
    rawMarkets: [
      {
        id: '1',
        underlyingAsset: metis['metis'].address,
        icon: metis['metis'].icon,
        decimals: metis['metis'].decimals,
        symbol: metis['metis'].symbol,
        name: metis['metis'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x7314Ef2CA509490f65F52CC8FC9E0675C66390b8',
        variableDebtTokenAddress: '0x0110174183e13D5Ea59D7512226c5D5A47bA2c40',
        isIsolated: true,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true,
        isStableForIsolated: true
      },
      {
        id: '2',
        underlyingAsset: metis['m.usdc'].address,
        icon: metis['m.usdc'].icon,
        decimals: metis['m.usdc'].decimals,
        symbol: metis['m.usdc'].symbol,
        name: metis['m.usdc'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x885C8AEC5867571582545F894A5906971dB9bf27',
        variableDebtTokenAddress: '0x571171a7EF1e3c8c83d47EF1a50E225E9c351380',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true,
        isStableForIsolated: true
      },
      {
        id: '3',
        underlyingAsset: metis['m.usdt'].address,
        icon: metis['m.usdt'].icon,
        decimals: metis['m.usdt'].decimals,
        symbol: metis['m.usdt'].symbol,
        name: metis['m.usdt'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0xd9fa75D14c26720d5ce7eE2530793a823e8f07b9',
        variableDebtTokenAddress: '0x6B45DcE8aF4fE5Ab3bFCF030d8fB57718eAB54e5',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true,
        isStableForIsolated: true
      },
      {
        id: '4',
        underlyingAsset: metis['weth'].address,
        icon: metis['weth'].icon,
        decimals: metis['weth'].decimals,
        symbol: metis['weth'].symbol,
        name: metis['weth'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x8acAe35059C9aE27709028fF6689386a44c09f3a',
        variableDebtTokenAddress: '0x8Bb19e3DD277a73D4A95EE434F14cE4B92898421',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true,
        isStableForIsolated: true
      },
      {
        id: '5',
        underlyingAsset: metis['m.dai'].address,
        icon: metis['m.dai'].icon,
        decimals: metis['m.dai'].decimals,
        symbol: metis['m.dai'].symbol,
        name: metis['m.dai'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x85ABAdDcae06efee2CB5F75f33b6471759eFDE24',
        variableDebtTokenAddress: '0x13Bd89aF338f3c7eAE9a75852fC2F1ca28B4DDbF',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      }
    ],
    CONTRACT_ABI,
    rewardToken
  },
  // gnosis
  100: {
    config: {
      ...baseConfig,
      chainName: 'Gnosis',
      nativeCurrency: gnosis['xdai'],
      nativeWrapCurrency: gnosis['weth'],
      rpcUrl: 'https://gnosis.drpc.org',
      aavePoolV3Address: '0xb50201558B00496A145fE76f7424749556E326D8',
      PoolDataProvider: '0x501B4c19dd9C2e06E94dA7b6D5Ed4ddA013EC741',
      wrappedTokenGatewayV3Address: '0xfE76366A986B72c3f2923e05E6ba07b7de5401e4',
      balanceProviderAddress: '0x4172E6aAEC070ACB31aaCE343A58c93E4C70f44D',
      incentivesProxy: '0xaD4F91D26254B6B0C6346b390dDA2991FDE2F20d' //CLAIM
    },
    rawMarkets: [
      // {
      //   id: '0',
      //   underlyingAsset: gnosis['wxdai'].address,
      //   icon: gnosis['xdai'].icon,
      //   decimals: gnosis['xdai'].decimals,
      //   symbol: gnosis['xdai'].symbol,
      //   name: gnosis['xdai'].name,
      //   supplyAPY: '',
      //   usageAsCollateralEnabled: true,
      //   borrowingEnabled: true,
      //   aTokenAddress: '0xd0Dd6cEF72143E22cCED4867eb0d5F2328715533',
      //   variableDebtTokenAddress: '0x281963D7471eCdC3A2Bd4503e24e89691cfe420D',
      //   isIsolated: false,
      //   availableLiquidity: 0,
      //   availableLiquidityUSD: '',
      //   variableBorrowAPY: '',
      //   supportPermit: false,
      //   LTV: 0,
      //   supportBorrow: true
      // },
      {
        id: '1',
        underlyingAsset: gnosis['wsteth'].address,
        icon: gnosis['wsteth'].icon,
        decimals: gnosis['wsteth'].decimals,
        symbol: gnosis['wsteth'].symbol,
        name: gnosis['wsteth'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x23e4E76D01B2002BE436CE8d6044b0aA2f68B68a',
        variableDebtTokenAddress: '0x9D881f67F20B49243c98f53d2B9E91E39d02Ae09',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '2',
        underlyingAsset: gnosis['wxdai'].address,
        icon: gnosis['wxdai'].icon,
        decimals: gnosis['wxdai'].decimals,
        symbol: gnosis['wxdai'].symbol,
        name: gnosis['wxdai'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0xd0Dd6cEF72143E22cCED4867eb0d5F2328715533',
        variableDebtTokenAddress: '0x281963D7471eCdC3A2Bd4503e24e89691cfe420D',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '3',
        underlyingAsset: gnosis['usdc'].address,
        icon: gnosis['usdc'].icon,
        decimals: gnosis['usdc'].decimals,
        symbol: gnosis['usdc'].symbol,
        name: gnosis['usdc'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0xc6B7AcA6DE8a6044E0e32d0c841a89244A10D284',
        variableDebtTokenAddress: '0x5F6f7B0a87CA3CF3d0b431Ae03EF3305180BFf4d',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        isStableForIsolated: true,
        supportBorrow: true
      },
      {
        id: '4',
        underlyingAsset: gnosis['eure'].address,
        icon: gnosis['eure'].icon,
        decimals: gnosis['eure'].decimals,
        symbol: gnosis['eure'].symbol,
        name: gnosis['eure'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0xEdBC7449a9b594CA4E053D9737EC5Dc4CbCcBfb2',
        variableDebtTokenAddress: '0xb96404e475f337A7E98e4a541C9b71309BB66c5A',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        isStableForIsolated: true,
        supportBorrow: true
      },
      {
        id: '5',
        underlyingAsset: gnosis['usdc.e'].address,
        icon: gnosis['usdc.e'].icon,
        decimals: gnosis['usdc.e'].decimals,
        symbol: gnosis['usdc.e'].symbol,
        name: gnosis['usdc.e'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0xC0333cb85B59a788d8C7CAe5e1Fd6E229A3E5a65',
        variableDebtTokenAddress: '0x37B9Ad6b5DC8Ad977AD716e92F49e9D200e58431',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        isStableForIsolated: true,
        supportBorrow: true
      },
      {
        id: '6',
        underlyingAsset: gnosis['gno'].address,
        icon: gnosis['gno'].icon,
        decimals: gnosis['gno'].decimals,
        symbol: gnosis['gno'].symbol,
        name: gnosis['gno'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0xA1Fa064A85266E2Ca82DEe5C5CcEC84DF445760e',
        variableDebtTokenAddress: '0xBc59E99198DbA71985A66E1713cC89FFEC53f7FC',
        isIsolated: true,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '7',
        underlyingAsset: gnosis['sDAI'].address,
        icon: gnosis['sDAI'].icon,
        decimals: gnosis['sDAI'].decimals,
        symbol: gnosis['sDAI'].symbol,
        name: gnosis['sDAI'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x7a5c3860a77a8DC1b225BD46d0fb2ac1C6D191BC',
        variableDebtTokenAddress: '',
        isIsolated: true,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      }
    ],
    CONTRACT_ABI
  },
  // base
  8453: {
    config: {
      ...baseConfig,
      chainName: 'Base',
      nativeCurrency: base['eth'],
      nativeWrapCurrency: base['weth'],
      rpcUrl: 'https://base.drpc.org',
      aavePoolV3Address: '0xA238Dd80C259a72e81d7e4664a9801593F98d1c5',
      PoolDataProvider: '0xd82a47fdebB5bf5329b09441C3DaB4b5df2153Ad',
      wrappedTokenGatewayV3Address: '0x729b3EA8C005AbC58c9150fb57Ec161296F06766',
      balanceProviderAddress: '0x5779b29B0a34577d927E8D511B595ef9abbFAE82',
      incentivesProxy: '0xf9cc4F0D883F1a1eb2c253bdb46c254Ca51E1F44' //CLAIM
    },
    rawMarkets: [
      {
        id: '1',
        underlyingAsset: base['weth'].address,
        icon: base['weth'].icon,
        decimals: 18,
        name: 'WETH',
        symbol: 'WETH',
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0xD4a0e0b9149BCee3C920d2E00b5dE09138fd8bb7',
        variableDebtTokenAddress: '0x24e6e0795b3c7c71D965fCc4f371803d1c1DcA1E',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '2',
        underlyingAsset: base['weeth'].address,
        icon: base['weeth'].icon,
        decimals: base['weeth'].decimals,
        symbol: base['weeth'].symbol,
        name: base['weeth'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x7C307e128efA31F540F2E2d976C995E0B65F51F6',
        variableDebtTokenAddress: '0x8D2e3F1f4b38AA9f1ceD22ac06019c7561B03901',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '3',
        underlyingAsset: base['usdc'].address,
        icon: base['usdc'].icon,
        decimals: base['usdc'].decimals,
        symbol: base['usdc'].symbol,
        name: base['usdc'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x4e65fE4DbA92790696d040ac24Aa414708F5c0AB',
        variableDebtTokenAddress: '0x59dca05b6c26dbd64b5381374aAaC5CD05644C28',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '4',
        underlyingAsset: base['usdbc'].address,
        icon: base['usdbc'].icon,
        decimals: base['usdbc'].decimals,
        symbol: base['usdbc'].symbol,
        name: base['usdbc'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x0a1d576f3eFeF75b330424287a95A366e8281D54',
        variableDebtTokenAddress: '0x7376b2F323dC56fCd4C191B34163ac8a84702DAB',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '5',
        underlyingAsset: base['cbeth'].address,
        icon: base['cbeth'].icon,
        decimals: base['cbeth'].decimals,
        symbol: base['cbeth'].symbol,
        name: base['cbeth'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0xcf3D55c10DB69f28fD1A75Bd73f3D8A2d9c595ad',
        variableDebtTokenAddress: '0x1DabC36f19909425f654777249815c073E8Fd79F',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '6',
        underlyingAsset: base['wsteth'].address,
        icon: base['wsteth'].icon,
        decimals: base['wsteth'].decimals,
        symbol: base['wsteth'].symbol,
        name: base['wsteth'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x99CBC45ea5bb7eF3a5BC08FB1B7E56bB2442Ef0D',
        variableDebtTokenAddress: '0x41A7C3f5904ad176dACbb1D99101F59ef0811DC1',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      }
    ],
    CONTRACT_ABI
  },
  // arbitrum
  42161: {
    config: {
      ...baseConfig,
      chainName: 'Arbitrum',
      nativeCurrency: arbitrum['eth'],
      nativeWrapCurrency: arbitrum['weth'],
      rpcUrl: 'https://arbitrum.drpc.org',
      aavePoolV3Address: '0x794a61358D6845594F94dc1DB02A252b5b4814aD',
      PoolDataProvider: '0x7F23D86Ee20D869112572136221e173428DD740B',
      wrappedTokenGatewayV3Address: '0x5760E34c4003752329bC77790B1De44C2799F8C3',
      balanceProviderAddress: '0xBc790382B3686abffE4be14A030A96aC6154023a',
      incentivesProxy: '0x929EC64c34a17401F460460D4B9390518E5B473e' //CLAIM
    },
    rawMarkets: [
      // {
      //   id: '1',
      //   underlyingAsset: arbitrum['weth'].address,
      //   icon: arbitrum['eth'].icon,
      //   decimals: 18,
      //   name: 'Ethereum',
      //   symbol: 'ETH',
      //   supplyAPY: '',
      //   usageAsCollateralEnabled: true,
      //   borrowingEnabled: true,
      //   aTokenAddress: '0xe50fA9b3c56FfB159cB0FCA61F5c9D750e8128c8',
      //   variableDebtTokenAddress: '0x0c84331e39d6658Cd6e6b9ba04736cC4c4734351',
      //   isIsolated: false,
      //   availableLiquidity: 0,
      //   availableLiquidityUSD: '',
      //   variableBorrowAPY: '',
      //   supportPermit: false,
      //   LTV: 0,
      //   supportBorrow: true
      // },
      {
        id: '2',
        underlyingAsset: arbitrum['wbtc'].address,
        icon: arbitrum['wbtc'].icon,
        decimals: arbitrum['wbtc'].decimals,
        symbol: arbitrum['wbtc'].symbol,
        name: arbitrum['wbtc'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x078f358208685046a11C85e8ad32895DED33A249',
        variableDebtTokenAddress: '0x92b42c66840C7AD907b4BF74879FF3eF7c529473',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '3',
        underlyingAsset: arbitrum['we-eth'].address,
        icon: arbitrum['we-eth'].icon,
        decimals: arbitrum['we-eth'].decimals,
        symbol: arbitrum['we-eth'].symbol,
        name: arbitrum['we-eth'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x8437d7C167dFB82ED4Cb79CD44B7a32A1dd95c77',
        variableDebtTokenAddress: '0x3ca5FA07689F266e907439aFd1fBB59c44fe12f6',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '4',
        underlyingAsset: arbitrum['usdc'].address,
        icon: arbitrum['usdc'].icon,
        decimals: arbitrum['usdc'].decimals,
        symbol: arbitrum['usdc'].symbol,
        name: arbitrum['usdc'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x625E7708f30cA75bfd92586e17077590C60eb4cD',
        variableDebtTokenAddress: '0xFCCf3cAbbe80101232d343252614b6A3eE81C989',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '5',
        underlyingAsset: arbitrum['usdt'].address,
        icon: arbitrum['usdt'].icon,
        decimals: arbitrum['usdt'].decimals,
        symbol: arbitrum['usdt'].symbol,
        name: arbitrum['usdt'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x6ab707Aca953eDAeFBc4fD23bA73294241490620',
        variableDebtTokenAddress: '0xfb00AC187a8Eb5AFAE4eACE434F493Eb62672df7',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '6',
        underlyingAsset: arbitrum['lusd'].address,
        icon: arbitrum['lusd'].icon,
        decimals: arbitrum['lusd'].decimals,
        symbol: arbitrum['lusd'].symbol,
        name: arbitrum['lusd'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x8ffDf2DE812095b1D19CB146E4c004587C0A0692',
        variableDebtTokenAddress: '0xA8669021776Bc142DfcA87c21b4A52595bCbB40a',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '7',
        underlyingAsset: arbitrum['dai'].address,
        icon: arbitrum['dai'].icon,
        decimals: arbitrum['dai'].decimals,
        symbol: arbitrum['dai'].symbol,
        name: arbitrum['dai'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x82E64f49Ed5EC1bC6e43DAD4FC8Af9bb3A2312EE',
        variableDebtTokenAddress: '0x8619d80FB0141ba7F184CbF22fd724116D9f7ffC',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '8',
        underlyingAsset: arbitrum['link'].address,
        icon: arbitrum['link'].icon,
        decimals: arbitrum['link'].decimals,
        symbol: arbitrum['link'].symbol,
        name: arbitrum['link'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x191c10Aa4AF7C30e871E70C95dB0E4eb77237530',
        variableDebtTokenAddress: '0x953A573793604aF8d41F306FEb8274190dB4aE0e',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      }
    ],
    CONTRACT_ABI
  },
  // avalanche
  43114: {
    config: {
      ...baseConfig,
      chainName: 'Avalanche',
      nativeCurrency: avalanche['avax'],
      nativeWrapCurrency: avalanche['wavax'],
      rpcUrl: 'https://avalanche.drpc.org',
      aavePoolV3Address: '0x794a61358D6845594F94dc1DB02A252b5b4814aD',
      PoolDataProvider: '0x7F23D86Ee20D869112572136221e173428DD740B',
      wrappedTokenGatewayV3Address: '0xCf3045a03F83ADfBCbA1f19Cb2cF4E19075F8668',
      balanceProviderAddress: '0xBc790382B3686abffE4be14A030A96aC6154023a',
      incentivesProxy: '0x929EC64c34a17401F460460D4B9390518E5B473e' //CLAIM
    },
    rawMarkets: [
      {
        id: '1',
        underlyingAsset: avalanche['usdc'].address,
        icon: avalanche['usdc'].icon,
        decimals: avalanche['usdc'].decimals,
        symbol: avalanche['usdc'].symbol,
        name: avalanche['usdc'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x625E7708f30cA75bfd92586e17077590C60eb4cD',
        variableDebtTokenAddress: '0xFCCf3cAbbe80101232d343252614b6A3eE81C989',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '3',
        underlyingAsset: avalanche['wavax'].address,
        icon: avalanche['wavax'].icon,
        decimals: avalanche['wavax'].decimals,
        symbol: avalanche['wavax'].symbol,
        name: avalanche['wavax'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x6d80113e533a2C0fe82EaBD35f1875DcEA89Ea97',
        variableDebtTokenAddress: '0x4a1c3aD6Ed28a636ee1751C69071f6be75DEb8B8',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '4',
        underlyingAsset: avalanche['usdt'].address,
        icon: avalanche['usdt'].icon,
        decimals: avalanche['usdt'].decimals,
        symbol: avalanche['usdt'].symbol,
        name: avalanche['usdt'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x6ab707Aca953eDAeFBc4fD23bA73294241490620',
        variableDebtTokenAddress: '0xfb00AC187a8Eb5AFAE4eACE434F493Eb62672df7',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '5',
        underlyingAsset: avalanche['weth.e'].address,
        icon: avalanche['weth.e'].icon,
        decimals: avalanche['weth.e'].decimals,
        symbol: avalanche['weth.e'].symbol,
        name: avalanche['weth.e'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0xe50fA9b3c56FfB159cB0FCA61F5c9D750e8128c8',
        variableDebtTokenAddress: '0x0c84331e39d6658Cd6e6b9ba04736cC4c4734351',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '6',
        underlyingAsset: avalanche['dai.e'].address,
        icon: avalanche['dai.e'].icon,
        decimals: avalanche['dai.e'].decimals,
        symbol: avalanche['dai.e'].symbol,
        name: avalanche['dai.e'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x82E64f49Ed5EC1bC6e43DAD4FC8Af9bb3A2312EE',
        variableDebtTokenAddress: '0x8619d80FB0141ba7F184CbF22fd724116D9f7ffC',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      }
    ],
    CONTRACT_ABI
  },
  // optimism
  10: {
    config: {
      ...baseConfig,
      chainName: 'Optimism',
      nativeCurrency: optimism['eth'],
      nativeWrapCurrency: optimism['weth'],
      rpcUrl: 'https://optimism.drpc.org',
      aavePoolV3Address: '0x794a61358D6845594F94dc1DB02A252b5b4814aD',
      PoolDataProvider: '0x7F23D86Ee20D869112572136221e173428DD740B',
      wrappedTokenGatewayV3Address: '0x60eE8b61a13c67d0191c851BEC8F0bc850160710',
      balanceProviderAddress: '0xBc790382B3686abffE4be14A030A96aC6154023a',
      incentivesProxy: '0x929EC64c34a17401F460460D4B9390518E5B473e' //CLAIM
    },
    rawMarkets: [
      // {
      //   id: '0',
      //   underlyingAsset: optimism['weth'].address,
      //   icon: optimism['eth'].icon,
      //   decimals: optimism['eth'].decimals,
      //   symbol: optimism['eth'].symbol,
      //   name: optimism['eth'].name,
      //   supplyAPY: '',
      //   usageAsCollateralEnabled: true,
      //   borrowingEnabled: true,
      //   aTokenAddress: '0xe50fA9b3c56FfB159cB0FCA61F5c9D750e8128c8',
      //   variableDebtTokenAddress: '0x0c84331e39d6658Cd6e6b9ba04736cC4c4734351',
      //   isIsolated: false,
      //   availableLiquidity: 0,
      //   availableLiquidityUSD: '',
      //   variableBorrowAPY: '',
      //   supportPermit: false,
      //   LTV: 0,
      //   supportBorrow: true
      // },
      {
        id: '1',
        underlyingAsset: optimism['usdc.e'].address,
        icon: optimism['usdc.e'].icon,
        decimals: optimism['usdc.e'].decimals,
        symbol: optimism['usdc.e'].symbol,
        name: optimism['usdc.e'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x625E7708f30cA75bfd92586e17077590C60eb4cD',
        variableDebtTokenAddress: '0xFCCf3cAbbe80101232d343252614b6A3eE81C989',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '2',
        underlyingAsset: optimism['usdt'].address,
        icon: optimism['usdt'].icon,
        decimals: optimism['usdt'].decimals,
        symbol: optimism['usdt'].symbol,
        name: optimism['usdt'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x6ab707Aca953eDAeFBc4fD23bA73294241490620',
        variableDebtTokenAddress: '0xfb00AC187a8Eb5AFAE4eACE434F493Eb62672df7',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '3',
        underlyingAsset: optimism['usdc'].address,
        icon: optimism['usdc'].icon,
        decimals: optimism['usdc'].decimals,
        symbol: optimism['usdc'].symbol,
        name: optimism['usdc'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x38d693cE1dF5AaDF7bC62595A37D667aD57922e5',
        variableDebtTokenAddress: '0x5D557B07776D12967914379C71a1310e917C7555',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '4',
        underlyingAsset: optimism['weth'].address,
        icon: optimism['weth'].icon,
        decimals: optimism['weth'].decimals,
        symbol: optimism['weth'].symbol,
        name: optimism['weth'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0xe50fA9b3c56FfB159cB0FCA61F5c9D750e8128c8',
        variableDebtTokenAddress: '0x0c84331e39d6658Cd6e6b9ba04736cC4c4734351',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '5',
        underlyingAsset: optimism['lusd'].address,
        icon: optimism['lusd'].icon,
        decimals: optimism['lusd'].decimals,
        symbol: optimism['lusd'].symbol,
        name: optimism['lusd'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x8Eb270e296023E9D92081fdF967dDd7878724424',
        variableDebtTokenAddress: '0xCE186F6Cccb0c955445bb9d10C59caE488Fea559',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '6',
        underlyingAsset: optimism['wbtc'].address,
        icon: optimism['wbtc'].icon,
        decimals: optimism['wbtc'].decimals,
        symbol: optimism['wbtc'].symbol,
        name: optimism['wbtc'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x078f358208685046a11C85e8ad32895DED33A249',
        variableDebtTokenAddress: '0x92b42c66840C7AD907b4BF74879FF3eF7c529473',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '7',
        underlyingAsset: optimism['dai'].address,
        icon: optimism['dai'].icon,
        decimals: optimism['dai'].decimals,
        symbol: optimism['dai'].symbol,
        name: optimism['dai'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x82E64f49Ed5EC1bC6e43DAD4FC8Af9bb3A2312EE',
        variableDebtTokenAddress: '0x8619d80FB0141ba7F184CbF22fd724116D9f7ffC',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '6',
        underlyingAsset: optimism['susd'].address,
        icon: optimism['susd'].icon,
        decimals: optimism['susd'].decimals,
        symbol: optimism['susd'].symbol,
        name: optimism['susd'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x6d80113e533a2C0fe82EaBD35f1875DcEA89Ea97',
        variableDebtTokenAddress: '0x4a1c3aD6Ed28a636ee1751C69071f6be75DEb8B8',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      }
    ],
    CONTRACT_ABI
  },
  // polygon
  137: {
    config: {
      ...baseConfig,
      chainName: 'Polygon',
      nativeCurrency: polygon['matic'],
      nativeWrapCurrency: polygon['wmatic'],
      rpcUrl: 'https://polygon.drpc.org',
      aavePoolV3Address: '0x794a61358D6845594F94dc1DB02A252b5b4814aD',
      PoolDataProvider: '0x7F23D86Ee20D869112572136221e173428DD740B',
      wrappedTokenGatewayV3Address: '0x60eE8b61a13c67d0191c851BEC8F0bc850160710',
      balanceProviderAddress: '0xBc790382B3686abffE4be14A030A96aC6154023a',
      incentivesProxy: '0x929EC64c34a17401F460460D4B9390518E5B473e' //CLAIM
    },
    rawMarkets: [
      // {
      //   id: '0',
      //   underlyingAsset: polygon['wmatic'].address,
      //   icon: polygon['matic'].icon,
      //   decimals: polygon['matic'].decimals,
      //   symbol: 'POL',
      //   name: 'POL',
      //   supplyAPY: '',
      //   usageAsCollateralEnabled: true,
      //   borrowingEnabled: true,
      //   aTokenAddress: '0x6d80113e533a2C0fe82EaBD35f1875DcEA89Ea97',
      //   variableDebtTokenAddress: '0x4a1c3aD6Ed28a636ee1751C69071f6be75DEb8B8',
      //   isIsolated: false,
      //   availableLiquidity: 0,
      //   availableLiquidityUSD: '',
      //   variableBorrowAPY: '',
      //   supportPermit: false,
      //   LTV: 0,
      //   supportBorrow: true
      // },
      // {
      //   id: '1',
      //   underlyingAsset: polygon['wmatic'].address,
      //   icon: polygon['matic'].icon,
      //   decimals: polygon['matic'].decimals,
      //   symbol: 'WPOL',
      //   name: 'WPOL',
      //   supplyAPY: '',
      //   usageAsCollateralEnabled: true,
      //   borrowingEnabled: true,
      //   aTokenAddress: '0x6d80113e533a2C0fe82EaBD35f1875DcEA89Ea97',
      //   variableDebtTokenAddress: '0x4a1c3aD6Ed28a636ee1751C69071f6be75DEb8B8',
      //   isIsolated: false,
      //   availableLiquidity: 0,
      //   availableLiquidityUSD: '',
      //   variableBorrowAPY: '',
      //   supportPermit: false,
      //   LTV: 0,
      //   supportBorrow: true
      // },
      {
        id: '2',
        underlyingAsset: polygon['dai'].address,
        icon: polygon['dai'].icon,
        decimals: polygon['dai'].decimals,
        symbol: polygon['dai'].symbol,
        name: polygon['dai'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x82E64f49Ed5EC1bC6e43DAD4FC8Af9bb3A2312EE',
        variableDebtTokenAddress: '0x8619d80FB0141ba7F184CbF22fd724116D9f7ffC',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '3',
        underlyingAsset: polygon['usdc'].address,
        icon: polygon['usdc'].icon,
        decimals: polygon['usdc'].decimals,
        symbol: polygon['usdc'].symbol,
        name: polygon['usdc'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0xA4D94019934D8333Ef880ABFFbF2FDd611C762BD',
        variableDebtTokenAddress: '0xE701126012EC0290822eEA17B794454d1AF8b030',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '4',
        underlyingAsset: polygon['usdc.e'].address,
        icon: polygon['usdc.e'].icon,
        decimals: polygon['usdc.e'].decimals,
        symbol: polygon['usdc.e'].symbol,
        name: polygon['usdc.e'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x625E7708f30cA75bfd92586e17077590C60eb4cD',
        variableDebtTokenAddress: '0xFCCf3cAbbe80101232d343252614b6A3eE81C989',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '5',
        underlyingAsset: polygon['usdt'].address,
        icon: polygon['usdt'].icon,
        decimals: polygon['usdt'].decimals,
        symbol: polygon['usdt'].symbol,
        name: polygon['usdt'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x6ab707Aca953eDAeFBc4fD23bA73294241490620',
        variableDebtTokenAddress: '0xfb00AC187a8Eb5AFAE4eACE434F493Eb62672df7',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '6',
        underlyingAsset: polygon['weth'].address,
        icon: polygon['weth'].icon,
        decimals: polygon['weth'].decimals,
        symbol: polygon['weth'].symbol,
        name: polygon['weth'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0xe50fA9b3c56FfB159cB0FCA61F5c9D750e8128c8',
        variableDebtTokenAddress: '0x0c84331e39d6658Cd6e6b9ba04736cC4c4734351',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '7',
        underlyingAsset: polygon['wbtc'].address,
        icon: polygon['wbtc'].icon,
        decimals: polygon['wbtc'].decimals,
        symbol: polygon['wbtc'].symbol,
        name: polygon['wbtc'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0x078f358208685046a11C85e8ad32895DED33A249',
        variableDebtTokenAddress: '0x92b42c66840C7AD907b4BF74879FF3eF7c529473',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '8',
        underlyingAsset: polygon['wsteth'].address,
        icon: polygon['wsteth'].icon,
        decimals: polygon['wsteth'].decimals,
        symbol: polygon['wsteth'].symbol,
        name: polygon['wsteth'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0xf59036CAEBeA7dC4b86638DFA2E3C97dA9FcCd40',
        variableDebtTokenAddress: '0x77fA66882a8854d883101Fb8501BD3CaD347Fc32',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      }
    ],
    CONTRACT_ABI
  },
  // zkSync
  324: {
    config: {
      ...baseConfig,
      chainName: 'zkSync',
      nativeCurrency: zkSync['eth'],
      nativeWrapCurrency: zkSync['weth'],
      rpcUrl: 'https://zkSync.drpc.org',
      aavePoolV3Address: '0x78e30497a3c7527d953c6B1E3541b021A98Ac43c',
      PoolDataProvider: '0x5F2A704cE47B373c908fE8A29514249469b52b99',
      wrappedTokenGatewayV3Address: '0xD5f6c8D402E0a0222f7FA132F9e80fDCC074df5C',
      balanceProviderAddress: '0xcb8Dc3C135e59B1252F057da44A8f43EE6B0dAB0',
      incentivesProxy: '0x37c972C9dDfC2138EBe33eC19dba063AB9f8966e' //CLAIM
    },
    rawMarkets: [
      {
        id: '1',
        underlyingAsset: zkSync['usdc'].address,
        icon: zkSync['usdc'].icon,
        decimals: zkSync['usdc'].decimals,
        name: zkSync['usdc'].name,
        symbol: zkSync['usdc'].symbol,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0xE977F9B2a5ccf0457870a67231F23BE4DaecfbDb',
        variableDebtTokenAddress: '0x0049250D15A8550c5a14Baa5AF5B662a93a525B9',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '2',
        underlyingAsset: zkSync['usdt'].address,
        icon: zkSync['usdt'].icon,
        decimals: zkSync['usdt'].decimals,
        symbol: zkSync['usdt'].symbol,
        name: zkSync['usdt'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0xC48574bc5358c967d9447e7Df70230Fdb469e4E7',
        variableDebtTokenAddress: '0x8992DB58077fe8C7B80c1B3a738eAe8A7BdDbA34',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '3',
        underlyingAsset: zkSync['weth'].address,
        icon: zkSync['weth'].icon,
        decimals: zkSync['weth'].decimals,
        symbol: zkSync['weth'].symbol,
        name: zkSync['weth'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0xb7b93bCf82519bB757Fd18b23A389245Dbd8ca64',
        variableDebtTokenAddress: '0x98dC737eA0E9bCb254c3F98510a71c5E11F74238',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '4',
        underlyingAsset: zkSync['wsteth'].address,
        icon: zkSync['wsteth'].icon,
        decimals: zkSync['wsteth'].decimals,
        symbol: zkSync['wsteth'].symbol,
        name: zkSync['wsteth'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0xd4e607633F3d984633E946aEA4eb71f92564c1c9',
        variableDebtTokenAddress: '0x6aD279F6523f6421fD5B0324a97D8F62eeCD80c8',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      },
      {
        id: '5',
        underlyingAsset: zkSync['zk'].address,
        icon: zkSync['zk'].icon,
        decimals: zkSync['zk'].decimals,
        symbol: zkSync['zk'].symbol,
        name: zkSync['zk'].name,
        supplyAPY: '',
        usageAsCollateralEnabled: true,
        borrowingEnabled: true,
        aTokenAddress: '0xd6cD2c0fC55936498726CacC497832052A9B2D1B',
        variableDebtTokenAddress: '0x6450fd7F877B5bB726F7Bc6Bf0e6ffAbd48d72ad',
        isIsolated: false,
        availableLiquidity: 0,
        availableLiquidityUSD: '',
        variableBorrowAPY: '',
        supportPermit: false,
        LTV: 0,
        supportBorrow: true
      }
    ],
    CONTRACT_ABI
  }
};

export default { basic, networks };
